### ISSUE TITLE
Sometimes game reports 8 mines when there are none

### ISSUE THREAD

**Issue by targos** [kamoroso94/minesweeper-chrome-app#1]
Example:
![image](https://cloud.githubusercontent.com/assets/2352663/21470576/64bccc20-ca8f-11e6-898b-371e4b681911.png)

**Comment by kamoroso94** [comment]
Thank you for bringing this bug to my attention.  I found the mistake at line 323, and I'm gonna make sure I didn't make the same mistake anywhere else.  I'll close when I update the repository.

**Comment by targos** [comment]
Here is another bug. I don't know if it's related:
![image](https://cloud.githubusercontent.com/assets/2352663/21484364/7d234d22-cb91-11e6-8c09-1d27db6d1673.png)

There is a 1 with two adjacent mines.

**Comment by targos** [comment]
And another one:
![image](https://cloud.githubusercontent.com/assets/2352663/21486568/d579f2c6-cbb6-11e6-8ff6-a9ac75a2fde4.png)
